# Generated by Django 2.2.7 on 2019-11-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='restaurant_app.ModelBase')),
                ('restaurant_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost_for_two', models.IntegerField()),
                ('currency', models.CharField(max_length=200)),
                ('table_booking', models.BooleanField(default=False)),
                ('online_delivery', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rating_color', models.CharField(max_length=100)),
                ('rating_text', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
            ],
            bases=('restaurant_app.modelbase',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant_app.ModelBase')),
                ('c_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('locality_verbose', models.CharField(max_length=600)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('restaurant_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='restaurant_app.Restaurant')),
            ],
            bases=('restaurant_app.modelbase',),
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant_app.ModelBase')),
                ('cuisine_name', models.CharField(max_length=200)),
                ('restaurant_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cuisine', to='restaurant_app.Restaurant')),
            ],
            bases=('restaurant_app.modelbase',),
        ),
    ]
