# Generated by Django 2.2.7 on 2019-11-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_auto_20191106_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant_app.ModelBase')),
                ('restaurant_details', models.FileField(upload_to='')),
                ('restaurant_address', models.FileField(upload_to='')),
            ],
            bases=('restaurant_app.modelbase',),
        ),
    ]
